export type Language = 'vi' | 'en';

export const copy = {
  vi: {
    language: 'Ngôn ngữ', local: 'Bản mẫu độc lập', title: 'So sánh phương án lưu trữ',
    subtitle: 'Cân nhắc chi phí cùng điều kiện sử dụng trước khi chọn kho.',
    captured: 'Báo giá chatbot đã ghi nhận', needs: 'Nhu cầu lưu trữ', reset: 'Khôi phục giá trị ban đầu',
    fields: { boxes: 'Số thùng', length: 'Dài (cm)', width: 'Rộng (cm)', height: 'Cao (cm)', months: 'Thời gian (tháng)', access: 'Giờ tự lấy đồ' },
    dimensions: 'Kích thước mỗi thùng', volume: 'Tổng thể tích', raw: 'Chưa làm tròn',
    fit: 'Thể tích không đảm bảo xếp vừa. Cần kiểm tra kích thước bên trong, cửa và khoảng trống sau khi tháo kệ.',
    errors: { positive: 'Nhập một số lớn hơn 0.', whole: 'Nhập một số nguyên dương hợp lệ.', time: 'Chọn giờ hợp lệ (00:00–23:59).', range: 'Giá trị quá lớn hoặc quá nhỏ để tính. Vui lòng giảm hoặc kiểm tra lại.' },
    invalidTitle: 'Cần kiểm tra lại thông tin', invalid: 'Hoàn tất các trường hợp lệ để xem so sánh báo giá.',
    options: 'Hai phương án trong báo giá', vat: 'Giá chưa gồm 8% VAT', lower: 'Giá ghi nhận thấp hơn · Có điều kiện', standard: 'Phương án tiêu chuẩn',
    services: { cool: 'Kho mát đặc biệt', standard: 'Kho tự quản thông thường' },
    month: '/ tháng', total: 'Tổng cho', months: 'tháng', beforeVat: 'trước VAT',
    access: 'Quyền truy cập', accessValue: 'Tự lấy đồ riêng tư 24/7', accessMatch: 'Đáp ứng giờ', according: 'theo cuộc trò chuyện đã ghi nhận',
    temperature: 'Điều kiện nhiệt độ', temperatures: { cool: 'Khoảng 15°C · chatbot cung cấp', standard: 'Không điều hòa (Non-AC)' },
    conditions: 'Điều kiện cần kiểm tra',
    eligibility: {
      cool: 'STOW đã xác nhận đồ cá nhân trong trò chuyện. Cần xác nhận lại điều kiện nhận đồ, nhiệt độ, điều khoản bảo vệ và việc tháo kệ trước khi đặt.',
      standard: 'Phù hợp để cân nhắc khi muốn điều kiện lưu trữ thông thường. Cần kiểm tra kích thước kho, giá và tình trạng còn chỗ.',
    },
    source: 'Nguồn: cuộc trò chuyện STOW của ứng viên · 15/09/2026',
    sourceTime: 'Ngày ghi nhận do ứng viên cung cấp; chưa rõ giờ chính xác.',
    availability: 'Chatbot cung cấp; cần xác minh trước khi đặt.',
    difference: 'Chênh lệch theo giá đã ghi nhận', monthlyDifference: 'Chênh lệch mỗi tháng',
    explanation: 'Giá thấp hơn, điều kiện khác nhau',
    coolReason: 'Theo báo giá đã ghi nhận, Cool Locker có giá thấp hơn, với điều kiện phù hợp về nhiệt độ, loại đồ và tình trạng còn chỗ hiện tại. Đây là Wine Locker được chuyển đổi; nhân viên cần kiểm tra và tháo kệ nếu cần.',
    standardReason: 'Kho 2 CBM Non-AC vẫn đáng cân nhắc nếu bạn muốn điều kiện lưu trữ thông thường. Chưa tự động chọn Cool Locker khi các điều kiện sử dụng chưa được xác nhận.',
    changed: 'Kích thước hoặc số thùng đã thay đổi. Hai báo giá chỉ để tham khảo; chưa có xác nhận phù hợp cho nhu cầu mới.',
    exceeds: 'Thể tích đồ vượt dung tích danh nghĩa của kho này.',
    exceedsCapacity: 'Vượt dung tích danh nghĩa',
    oneExceedsHeading: 'Một phương án vượt dung tích',
    bothExceedsHeading: 'Cần phương án lưu trữ khác',
    oneExceedsSummary: 'Một phương án vượt dung tích danh nghĩa; không thể coi giá ghi nhận là so sánh phù hợp cho nhu cầu hiện tại.',
    bothExceedsSummary: 'Cả hai phương án đều vượt dung tích danh nghĩa. Cần báo giá mới cho nhu cầu hiện tại.',
    oneExceedsExplanation: 'Phương án vượt dung tích không thể được coi là lựa chọn thay thế phù hợp cho nhu cầu lưu trữ hiện tại, dù giá ghi nhận vẫn được giữ lại để tham khảo.',
    bothExceedsExplanation: 'Không phương án ghi nhận nào có đủ dung tích danh nghĩa cho nhu cầu hiện tại. Cần liên hệ lấy báo giá mới thay vì dựa vào so sánh giá này.',
    estimate: 'Tổng tiền = giá tháng đã ghi nhận × số tháng; chưa xác minh giảm giá, phí khác hoặc điều khoản hiện tại.',
    verifyTitle: 'Xác minh trước khi đặt', verify: 'Kiểm tra tình trạng còn chỗ hiện tại',
    verifyNotice: 'Tình trạng còn chỗ phải được xác minh trước khi đặt. Giá và thông tin trên do chatbot cung cấp, chưa được kiểm chứng độc lập.',
    bookingNotice: 'Mở trang đặt chỗ chung của MyStorage. Cần xác nhận điều kiện Cool Locker và danh mục Wine Storage trước khi tiếp tục.',
    sourcesTitle: 'Nguồn tham khảo', sourceNames: { selfStorage: 'Kho tự quản', sizeGuide: 'Hướng dẫn kích thước', wineStorage: 'Kho rượu' },
    sourceBoundary: 'Các trang công khai cung cấp bối cảnh dịch vụ, không xác nhận giá hoặc chỗ trống trong báo giá này.',
    photoAlt: 'Khách mở khóa cửa kho MyStorage bằng điện thoại', photoCaption: 'Ảnh kho tự quản từ MyStorage; không phải ảnh xác minh Cool Locker.',
  },
  en: {
    language: 'Language', local: 'Independent prototype', title: 'Compare storage options',
    subtitle: 'Consider cost and storage conditions together before choosing a unit.',
    captured: 'Captured chatbot quote', needs: 'Storage needs', reset: 'Reset to original values',
    fields: { boxes: 'Number of boxes', length: 'Length (cm)', width: 'Width (cm)', height: 'Height (cm)', months: 'Duration (months)', access: 'Required self-access time' },
    dimensions: 'Dimensions per box', volume: 'Total volume', raw: 'Unrounded',
    fit: 'Volume does not establish physical fit. Verify internal dimensions, the door and usable space after rack removal.',
    errors: { positive: 'Enter a number greater than 0.', whole: 'Enter a valid positive whole number.', time: 'Choose a valid time (00:00–23:59).', range: 'Values are too large or small to calculate. Please check or reduce them.' },
    invalidTitle: 'Check your storage details', invalid: 'Complete the fields with valid values to see the quote comparison.',
    options: 'Two options in the captured quote', vat: 'Prices exclude 8% VAT', lower: 'Lower captured price · Conditional', standard: 'Standard option',
    services: { cool: 'Special Cool Locker', standard: 'Standard Self Storage' },
    month: '/ month', total: 'Total for', months: 'months', beforeVat: 'before VAT',
    access: 'Access', accessValue: '24/7 private self-access', accessMatch: 'Meets access at', according: 'according to the captured conversation',
    temperature: 'Temperature conditions', temperatures: { cool: 'Approximately 15°C · chatbot-reported', standard: 'Non-air-conditioned (Non-AC)' },
    conditions: 'Conditions to verify',
    eligibility: {
      cool: 'STOW confirmed personal items conversationally. Reconfirm item eligibility, temperature, protection terms and rack removal before booking.',
      standard: 'Worth considering for ordinary storage conditions. Verify unit dimensions, price and current availability.',
    },
    source: 'Source: candidate STOW chat · captured 15 Sep 2026',
    sourceTime: 'Capture date provided by the candidate; exact time unknown.',
    availability: 'Chatbot-reported; verify before booking.',
    difference: 'Difference at captured prices', monthlyDifference: 'Monthly difference',
    explanation: 'Lower price, different conditions',
    coolReason: 'Based on the captured quote, the Cool Locker has the lower price, subject to temperature, item eligibility and current availability. It is a repurposed Wine Locker; staff should inspect and remove racks if necessary.',
    standardReason: 'The 2 CBM Non-AC unit may be preferable for ordinary storage conditions. The Cool Locker is not automatically selected while its conditions remain unverified.',
    changed: 'Box dimensions or count have changed. Both quotes are reference prices only; suitability for the new needs has not been confirmed.',
    exceeds: 'Your item volume exceeds this unit’s nominal capacity.',
    exceedsCapacity: 'Exceeds nominal capacity',
    oneExceedsHeading: 'One option exceeds nominal capacity',
    bothExceedsHeading: 'A different storage option is needed',
    oneExceedsSummary: 'One option exceeds nominal capacity; captured prices cannot be treated as a suitable comparison for the current needs.',
    bothExceedsSummary: 'Neither captured option has sufficient nominal capacity. A new quote is needed for the current needs.',
    oneExceedsExplanation: 'The option that exceeds nominal capacity cannot be treated as a suitable alternative for the current storage needs, although its captured price is retained as reference information.',
    bothExceedsExplanation: 'Neither captured option has sufficient nominal capacity for the current needs. Contact for a new quote rather than relying on this price comparison.',
    estimate: 'Total = captured monthly price × months; discounts, other fees and current terms have not been verified.',
    verifyTitle: 'Verify before booking', verify: 'Verify current availability',
    verifyNotice: 'Availability must be verified before booking. Prices and details are chatbot-reported and have not been independently verified.',
    bookingNotice: 'Opens MyStorage’s general booking page. Confirm Cool Locker conditions and the Wine Storage category before proceeding.',
    sourcesTitle: 'Reference sources', sourceNames: { selfStorage: 'Self storage', sizeGuide: 'Size guide', wineStorage: 'Wine storage' },
    sourceBoundary: 'Public pages provide service context; they do not verify the prices or availability in this quote.',
    photoAlt: 'Customer opening a MyStorage locker with a phone', photoCaption: 'Self-storage photo from MyStorage; not verification of the Cool Locker.',
  },
};
